### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by danko79** [tebl/C64-Joystick-Switcher#1]
Hi, i need a some PCBs from you, can answer me. Thanks

**Comment by tebl** [comment]
If you need the PCBs, you can order them from PCBway.com, more specifically https://www.pcbway.com/project/shareproject/Commodore_64_Joystick_Switcher__Revision_C_.html?inviteid=88707.

**Comment by danko79** [comment]
Hi,you don't have a your PCB for sale? I need a some projects....
