### ISSUE TITLE
Autofire not Working

### ISSUE THREAD

**Issue by fbugallo** [tebl/C64-Joystick-Switcher#5]
Hi, I can't get Auto Fire to work.

I am using PCBWAY revision C (https://www.pcbway.com/project/shareproject/Commodore_64_Joystick_Switcher__Revision_C_.html).

Assemble everything as indicated, and the other functionalities work perfectly.

I changed the 555 chip for a new one to see if it was the problem, I adjusted the preset and I didn't get any change at all, just no autofire.

What could it be? I can upload photos if you think necessary.

Thanks

**Comment by fbugallo** [comment]
I changed the 555 for another brand and it worked fine. That same 555 worked ok for the port select function. I assume there is an incompatibility or it was a fake.

**Comment by tebl** [comment]
Is JP2 set with pins 1-2 jumped? A broken RV1 would cause such an issue,
measure resistance across it to verify. Mounting the electrolytic the wrong
way around may cause similar issues. Then there's always the possibility of
a short somewhere.

See schematic for places that are expected to be linked and ones that are
not.

fre. 25. mar. 2022, 15:10 skrev fbugallo ***@***.***>:
